services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - backend/app/secrets.env
    volumes:
      - ./backend/data:/app/backend/data
    restart: unless-stopped
